---
# tasks file for deploy_docker_image
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release' ]

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  apt: update_cache=yes name=docker-ce state=latest
        
- name: Start and enable Docker
  service: name=docker state=started enabled=yes

- name: Download “tutum/hello-world” image
  shell: docker pull tutum/hello-world:latest
        
- name: Change docker-daemon dns
  copy: 
    src:  "daemon.json"
    dest: "/etc/docker/"
  notify: Restart Docker

- name: Start “tutum/hello-world” image with 1080:80 ports 
  shell: docker run -d -p 1080:80 tutum/hello-world
