---
# tasks file for install_nginx
- name: Install Nginx
  apt:
    name=nginx
    state=latest

- name: Start and enable Nginx
  service:
    name=nginx
    state=started
    enabled=yes

- name: Allow port 80
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT

- name: Copy load_balancer.conf
  template:
    src: templates/load_balancer.conf.j2
    dest: "/etc/nginx/conf.d/load_balancer.conf"

- name: Delete default server configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx